### ISSUE TITLE
API Key invalid

### ISSUE THREAD

**Issue by mamedia-edv** [adobe/stock-api-sdk#3]
Hi guys,

I'm trying to use the Adobe Stock API in combination with this PHP SDK for Adobe Stock and hope that someone can help me solve the issues that I'm currently facing.  I created a new integration at the adobe console which provided me with the necessary API key and client secret for OAuth. When I'm now sending a request with Postman using the given API key everything works fine like you can see here:

![postman](https://forums.adobe.com/servlet/JiveServlet/downloadImage/2-10106278-1396027/900-591/postman.jpeg)

However when I'm trying to do the same basic request with the Stock API PHP library I always get the response:

`{"error_code":"403003","message":"Api Key is invalid"}`

Since the library is using GuzzleHttp I dumped the header of the sent request in order to debug a little further and to confirm that the correct api key has been sent.

![header](https://forums.adobe.com/servlet/JiveServlet/downloadImage/2-10106278-1396169/header.jpeg)

I blackened most of the api key but I'm 100% sure that it is correct.

Has someone of you guys experienced something like that? Or has someone a advice on how I should further debug this issue?

By the way: I also obtained an access token using the User Auth UI but apparently the token is not necessary for requests on /Search/Files. 

Thanks for your help!

Andreas

**Comment by chfabbro** [comment]
Hi Andreas,

There is an issue in the SDKs that the configuration defaults to the Adobe internal staging environment instead of the production environment. Unfortunately, external users do not have access to our private staging instance, so are unable to use it. The API key you created only works in the production environment, and is invalid in staging. 

Therefore, the quick fix is to add the environment to when creating your client.

```
$client = new AdobeStock('AdobeStockClient1', 'Adobe Stock Lib/1.0.0', 'PROD', new Http());
```

I apologize that this is not even mentioned or documented! For your information, the value above is located [here](https://github.com/adobe/stock-api-sdk/blob/master/stock-api-libphp/src/Core/Constants.php).

Please let me know if this resolves the problem, so I can close this issue. Bonus points for using Postman! 👍 

To answer your second comment, yes, the token is not required to use the Search API. However, you can use it to get the licensed state of an asset. For example, if you search and use the `$results_columns['IS_LICENSED']` result column, then the results will be marked true or false if the asset has been licensed.

You can find a good discussion of this at [Licensing assets and stuff](https://www.adobe.io/apis/creativecloud/stock/docs/getting-started/01-getting-started_master/06-licensing-assets.html).

Thanks!
Christopher

**Comment by mamedia-edv** [comment]
Hi Christopher,

thank you so much for your quick and detailed response!
That indeed resolved the problem! I've assumed that STAGE was referring to the development state of my integration so it didn't bother me too much. Now that you explained it to me and I took a closer look at this part it's quiet obvious why it didn't work. It also makes sense to me that the access token is not necessary for the search api.

Thanks again and have a great day!
Andreas

**Comment by chfabbro** [comment]
Hi Andreas,

Thank you for closing the issue. I have opened a ticket with our team to change the default environment to production, to prevent this from happening in the future.

Thanks!
Christopher
