### ISSUE TITLE
Is this 'umbrella' repo needed?

### ISSUE THREAD

**Issue by filmaj** [adobe/stock-api-sdk#7]
I'm simply looking to have a discussion about this.

Since we have the actual language implementations elsewhere, do we find this repo provides value? Perhaps from an issue-gathering standpoint? Or maybe it does not?

I'm in spring cleaning mode for github.com/adobe so thought I'd throw this out as a question 😄

**Comment by chfabbro** [comment]
The history is that originally this was one repository, and was approved by the Open Source all together. Since then, it became more practical to keep them separate. However, from a documentation and customer support standpoint, it is much more convenient to have a single landing page to send customers. Otherwise, you will need to either send a partner multiple links, or ask them exactly which SDK they want. I believe it is more elegant to have a "landing page" for the SDKs rather than rely on lots of links getting separated, especially if a developer finds one SDK and is unaware that others exist.

**Comment by filmaj** [comment]
OK, that's fair. Thanks for the info! I will close this.
